export const athletes = [
  {
    name: "Ana Marcela Cunha",
    discipline: "Águas Abertas",
    gender: "Feminino",
  },
  { name: "Viviane Jungblut", discipline: "Águas Abertas", gender: "Feminino" },
  { name: "Guilherme Costa", discipline: "Águas Abertas", gender: "Masculino" },
  { name: "Ana Carolina Azevedo", discipline: "Atletismo", gender: "Feminino" },
  {
    name: "Ana Caroline Miguel da Silva",
    discipline: "Atletismo",
    gender: "Feminino",
  },
  {
    name: "Andressa Oliveira de Morais",
    discipline: "Atletismo",
    gender: "Feminino",
  },
  {
    name: "Chayenne Pereira da Silva",
    discipline: "Atletismo",
    gender: "Feminino",
  },
  { name: "Eliane Martins", discipline: "Atletismo", gender: "Feminino" },
  { name: "Érica Sena", discipline: "Atletismo", gender: "Feminino" },
  { name: "Flávia Maria de Lima", discipline: "Atletismo", gender: "Feminino" },
  {
    name: "Gabriela de Souza Muniz",
    discipline: "Atletismo",
    gender: "Feminino",
  },
  {
    name: "Gabriele Sousa dos Santos",
    discipline: "Atletismo",
    gender: "Feminino",
  },
  {
    name: "Izabela Rodrigues da Silva",
    discipline: "Atletismo",
    gender: "Feminino",
  },
  {
    name: "Jucilene Sales de Lima",
    discipline: "Atletismo",
    gender: "Feminino",
  },
  {
    name: "Juliana de Menis Campos",
    discipline: "Atletismo",
    gender: "Feminino",
  },
  { name: "Lissandra Campos", discipline: "Atletismo", gender: "Feminino" },
  { name: "Lorraine Barbosa", discipline: "Atletismo", gender: "Feminino" },
  {
    name: "Tatiane Raquel da Silva",
    discipline: "Atletismo",
    gender: "Feminino",
  },
  { name: "Tiffani Marinho", discipline: "Atletismo", gender: "Feminino" },
  { name: "Valdileia Martins", discipline: "Atletismo", gender: "Feminino" },
  { name: "Vitória Rosa", discipline: "Atletismo", gender: "Feminino" },
  { name: "Viviane Lyra", discipline: "Atletismo", gender: "Feminino" },
  { name: "Alison dos Santos", discipline: "Atletismo", gender: "Masculino" },
  {
    name: "Almir Cunha dos Santos",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  { name: "Caio Bonfim", discipline: "Atletismo", gender: "Masculino" },
  {
    name: "Daniel Ferreira do Nascimento",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  { name: "Darlan Romani", discipline: "Atletismo", gender: "Masculino" },
  { name: "Douglas Hernandes", discipline: "Atletismo", gender: "Masculino" },
  {
    name: "Eduardo Rodrigues de Deus",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  { name: "Erik Cardoso", discipline: "Atletismo", gender: "Masculino" },
  { name: "Felipe Bardi", discipline: "Atletismo", gender: "Masculino" },
  {
    name: "Fernando Carvalho Ferreira",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  {
    name: "Gabriel Aparecido Garcia",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  {
    name: "Jadson Erick Soares Lima",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  {
    name: "José Fernando Ferreira Santana",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  { name: "Lucas Carvalho", discipline: "Atletismo", gender: "Masculino" },
  {
    name: "Lucas Conceição Vilar",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  {
    name: "Lucas Marcelino dos Santos",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  { name: "Luiz Maurício Dias", discipline: "Atletismo", gender: "Masculino" },
  {
    name: "Matheus Lima da Silva",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  {
    name: "Paulo André Camilo de Oliveira",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  {
    name: "Pedro Henrique Nunes",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  { name: "Rafael Pereira", discipline: "Atletismo", gender: "Masculino" },
  { name: "Renan Gallina", discipline: "Atletismo", gender: "Masculino" },
  {
    name: "Welington da Silva Morais",
    discipline: "Atletismo",
    gender: "Masculino",
  },
  { name: "Juliana Viana", discipline: "Badminton", gender: "Feminino" },
  { name: "Ygor Coelho", discipline: "Badminton", gender: "Masculino" },
  { name: "Yago", discipline: "Basquete", gender: "Masculino" },
  { name: "Raulzinho", discipline: "Basquete", gender: "Masculino" },
  { name: "Cristiano Felício", discipline: "Basquete", gender: "Masculino" },
  { name: "Didi Louzada", discipline: "Basquete", gender: "Masculino" },
  { name: "Vitor Benite", discipline: "Basquete", gender: "Masculino" },
  { name: "Marcelinho Huertas", discipline: "Basquete", gender: "Masculino" },
  { name: "Gui Santos", discipline: "Basquete", gender: "Masculino" },
  { name: "Léo Meindl", discipline: "Basquete", gender: "Masculino" },
  { name: "Elinho Corazza", discipline: "Basquete", gender: "Masculino" },
  { name: "Alexey", discipline: "Basquete", gender: "Masculino" },
  { name: "Georginho de Paula", discipline: "Basquete", gender: "Masculino" },
  {
    name: "João Marcelo Maozinha",
    discipline: "Basquete",
    gender: "Masculino",
  },
  { name: "Bruno Caboclo", discipline: "Basquete", gender: "Masculino" },
  { name: "Lucas Dias", discipline: "Basquete", gender: "Masculino" },
  { name: "Bárbara Santos", discipline: "Boxe", gender: "Feminino" },
  { name: "Beatriz Ferreira", discipline: "Boxe", gender: "Feminino" },
  { name: "Caroline Almeida", discipline: "Boxe", gender: "Feminino" },
  { name: "Jucielen Romeu", discipline: "Boxe", gender: "Feminino" },
  { name: "Tatiana Chagas", discipline: "Boxe", gender: "Feminino" },
  { name: "Abner Teixeira", discipline: "Boxe", gender: "Masculino" },
  { name: "Keno Marley", discipline: "Boxe", gender: "Masculino" },
  { name: "Luiz Oliveira", discipline: "Boxe", gender: "Masculino" },
  { name: "Michael Trindade", discipline: "Boxe", gender: "Masculino" },
  { name: "Wanderley Pereira", discipline: "Boxe", gender: "Masculino" },
  { name: "Ana Sátila", discipline: "Canoagem Slalom", gender: "Feminino" },
  {
    name: "Pedro Gonçalves",
    discipline: "Canoagem Slalom",
    gender: "Masculino",
  },
  {
    name: "Isaquias Queiroz",
    discipline: "Canoagem Velocidade",
    gender: "Masculino",
  },
  {
    name: "Jacky Godmann",
    discipline: "Canoagem Velocidade",
    gender: "Masculino",
  },
  {
    name: "Mateus Nunes",
    discipline: "Canoagem Velocidade",
    gender: "Masculino",
  },
  {
    name: "Vagner Souta",
    discipline: "Canoagem Velocidade",
    gender: "Masculino",
  },
  {
    name: "Valdenice Conceição",
    discipline: "Canoagem Velocidade",
    gender: "Feminino",
  },
  {
    name: "Ana Paula Vergutz",
    discipline: "Canoagem Velocidade",
    gender: "Feminino",
  },
  { name: "Paola Reis", discipline: "Ciclismo BMX Racing", gender: "Feminino" },
  {
    name: "Gustavo Bala Loka",
    discipline: "Ciclismo BMX Freestyle",
    gender: "Masculino",
  },
  {
    name: "Ana Vitoria Magalhães",
    discipline: "Ciclismo Estrada",
    gender: "Feminino",
  },
  {
    name: "Vinicius Rangel",
    discipline: "Ciclismo Estrada",
    gender: "Masculino",
  },
  {
    name: "Raiza Goulão",
    discipline: "Ciclismo Mountain Bike",
    gender: "Feminino",
  },
  {
    name: "Ulan Galinski",
    discipline: "Ciclismo Mountain Bike",
    gender: "Masculino",
  },
  { name: "Mariana Pistoia", discipline: "Esgrima", gender: "Feminino" },
  { name: "Nathalie Moellhausen", discipline: "Esgrima", gender: "Feminino" },
  { name: "Guilherme Toldo", discipline: "Esgrima", gender: "Masculino" },
  { name: "Lorena", discipline: "Futebol", gender: "Feminino" },
  { name: "Tainá", discipline: "Futebol", gender: "Feminino" },
  { name: "Tarciane", discipline: "Futebol", gender: "Feminino" },
  { name: "Rafaelle", discipline: "Futebol", gender: "Feminino" },
  { name: "Thais Ferreira", discipline: "Futebol", gender: "Feminino" },
  { name: "Antônia", discipline: "Futebol", gender: "Feminino" },
  { name: "Tamires", discipline: "Futebol", gender: "Feminino" },
  { name: "Yasmim", discipline: "Futebol", gender: "Feminino" },
  { name: "Yaya", discipline: "Futebol", gender: "Feminino" },
  { name: "Duda Sampaio", discipline: "Futebol", gender: "Feminino" },
  { name: "Ana Vitória", discipline: "Futebol", gender: "Feminino" },
  { name: "Gabi Portilho", discipline: "Futebol", gender: "Feminino" },
  { name: "Adriana", discipline: "Futebol", gender: "Feminino" },
  { name: "Kerolin", discipline: "Futebol", gender: "Feminino" },
  { name: "Ludmilla", discipline: "Futebol", gender: "Feminino" },
  { name: "Marta", discipline: "Futebol", gender: "Feminino" },
  { name: "Jheniffer", discipline: "Futebol", gender: "Feminino" },
  { name: "Gabi Nunes", discipline: "Futebol", gender: "Feminino" },
  {
    name: "Flávia Saraiva",
    discipline: "Ginástica Artística",
    gender: "Feminino",
  },
  {
    name: "Jade Barbosa",
    discipline: "Ginástica Artística",
    gender: "Feminino",
  },
  {
    name: "Julia Soares",
    discipline: "Ginástica Artística",
    gender: "Feminino",
  },
  {
    name: "Lorrane Oliveira",
    discipline: "Ginástica Artística",
    gender: "Feminino",
  },
  {
    name: "Rebeca Andrade",
    discipline: "Ginástica Artística",
    gender: "Feminino",
  },
  {
    name: "Arthur Nory",
    discipline: "Ginástica Artística",
    gender: "Masculino",
  },
  {
    name: "Diogo Soares",
    discipline: "Ginástica Artística",
    gender: "Masculino",
  },
  {
    name: "Bárbara Domingos",
    discipline: "Ginástica Rítmica",
    gender: "Feminino",
  },
  {
    name: "Débora Medrado",
    discipline: "Ginástica Rítmica",
    gender: "Feminino",
  },
  {
    name: "Maria Eduarda Arakaki",
    discipline: "Ginástica Rítmica",
    gender: "Feminino",
  },
  {
    name: "Nicole Pircio",
    discipline: "Ginástica Rítmica",
    gender: "Feminino",
  },
  {
    name: "Sofia Madeira",
    discipline: "Ginástica Rítmica",
    gender: "Feminino",
  },
  {
    name: "Victória Borges",
    discipline: "Ginástica Rítmica",
    gender: "Feminino",
  },
  {
    name: "Camilla Lopes",
    discipline: "Ginástica Trampolim",
    gender: "Feminino",
  },
  {
    name: "Rayan Castro",
    discipline: "Ginástica Trampolim",
    gender: "Masculino",
  },
  { name: "Gabi Moreschi", discipline: "Handebol", gender: "Feminino" },
  { name: "Renata Arruda", discipline: "Handebol", gender: "Feminino" },
  { name: "Bruna de Paula", discipline: "Handebol", gender: "Feminino" },
  { name: "Gabriela Bitolo", discipline: "Handebol", gender: "Feminino" },
  { name: "Giulia Guarieiro", discipline: "Handebol", gender: "Feminino" },
  { name: "Jhennifer dos Santos", discipline: "Handebol", gender: "Feminino" },
  { name: "Kelly Rosa", discipline: "Handebol", gender: "Feminino" },
  { name: "Mariane Fernandes", discipline: "Handebol", gender: "Feminino" },
  { name: "Patrícia Matieli", discipline: "Handebol", gender: "Feminino" },
  { name: "Adriana Cardoso", discipline: "Handebol", gender: "Feminino" },
  { name: "Larissa Araújo", discipline: "Handebol", gender: "Feminino" },
  { name: "Jéssica Quintino", discipline: "Handebol", gender: "Feminino" },
  { name: "Marcela Arounian", discipline: "Handebol", gender: "Feminino" },
  { name: "Tamires Araújo", discipline: "Handebol", gender: "Feminino" },
  {
    name: "João Victor Oliva",
    discipline: "Hipismo Adestramento",
    gender: "Masculino",
  },
  {
    name: "Carlos Ramadam Parro",
    discipline: "Hipismo Completo",
    gender: "Masculino",
  },
  {
    name: "Marcio Carvalho Jorge",
    discipline: "Hipismo Completo",
    gender: "Masculino",
  },
  {
    name: "Rafael Mamprim Losano",
    discipline: "Hipismo Completo",
    gender: "Masculino",
  },
  {
    name: "Ruy Leme da Fonseca",
    discipline: "Hipismo Completo",
    gender: "Masculino",
  },
  { name: "Yuri Mansur", discipline: "Hipismo Saltos", gender: "Masculino" },
  {
    name: "Stephan de Freitas Barcha",
    discipline: "Hipismo Saltos",
    gender: "Masculino",
  },
  { name: "Rodrigo Pessoa", discipline: "Hipismo Saltos", gender: "Masculino" },
  { name: "Pedro Veniss", discipline: "Hipismo Saltos", gender: "Masculino" },
  { name: "Natasha Ferreira", discipline: "Judô", gender: "Feminino" },
  { name: "Larissa Pimenta", discipline: "Judô", gender: "Feminino" },
  { name: "Rafaela Silva", discipline: "Judô", gender: "Feminino" },
  { name: "Ketleyn Quadros", discipline: "Judô", gender: "Feminino" },
  { name: "Mayra Aguiar", discipline: "Judô", gender: "Feminino" },
  { name: "Beatriz Souza", discipline: "Judô", gender: "Feminino" },
  { name: "Michel Augusto", discipline: "Judô", gender: "Masculino" },
  { name: "William Lima", discipline: "Judô", gender: "Masculino" },
  { name: "Daniel Cargnin", discipline: "Judô", gender: "Masculino" },
  { name: "Guilherme Schimidt", discipline: "Judô", gender: "Masculino" },
  { name: "Rafael Macedo", discipline: "Judô", gender: "Masculino" },
  { name: "Leonardo Gonçalves", discipline: "Judô", gender: "Masculino" },
  { name: "Rafael Silva", discipline: "Judô", gender: "Masculino" },
  {
    name: "Amanda Schott",
    discipline: "Levantamento de Peso",
    gender: "Feminino",
  },
  {
    name: "Laura Amaro",
    discipline: "Levantamento de Peso",
    gender: "Feminino",
  },
  { name: "Ana Carolina Vieira", discipline: "Natação", gender: "Feminino" },
  { name: "Beatriz Dizotti", discipline: "Natação", gender: "Feminino" },
  { name: "Gabrielle Roncatto", discipline: "Natação", gender: "Feminino" },
  { name: "Giovana Reis", discipline: "Natação", gender: "Feminino" },
  { name: "Maria Fernanda Costa", discipline: "Natação", gender: "Feminino" },
  { name: "Maria Paula Heitmann", discipline: "Natação", gender: "Feminino" },
  { name: "Stephanie Balduccini", discipline: "Natação", gender: "Feminino" },
  { name: "Breno Correia", discipline: "Natação", gender: "Masculino" },
  { name: "Eduardo Moraes", discipline: "Natação", gender: "Masculino" },
  { name: "Fernando Scheffer", discipline: "Natação", gender: "Masculino" },
  { name: "Gabriel Santos", discipline: "Natação", gender: "Masculino" },
  { name: "Guilherme Basseto", discipline: "Natação", gender: "Masculino" },
  { name: "Guilherme Caribé", discipline: "Natação", gender: "Masculino" },
  { name: "Kayky Mota", discipline: "Natação", gender: "Masculino" },
  { name: "Marcelo Chierighini", discipline: "Natação", gender: "Masculino" },
  { name: "Murilo Sartori", discipline: "Natação", gender: "Masculino" },
  { name: "Nicolas Albiero", discipline: "Natação", gender: "Masculino" },
  {
    name: "Isabella Abreu",
    discipline: "Pentatlo Moderno",
    gender: "Feminino",
  },
  { name: "Beatriz Tavares", discipline: "Remo", gender: "Feminino" },
  { name: "Lucas Verthein", discipline: "Remo", gender: "Masculino" },
  { name: "Bianca Silva", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Gabriela Lima", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Gisele Gomes", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Luiza Campos", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Marcelle Souza", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Mariana Nicolau", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Marina Fioravanti", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Milena Mariano", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Raquel Kochhann", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Thalia Costa", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Thalita Costa", discipline: "Rúgbi", gender: "Feminino" },
  { name: "Yasmim Soares", discipline: "Rúgbi", gender: "Feminino" },
  {
    name: "Ingrid Oliveira",
    discipline: "Saltos Ornamentais",
    gender: "Feminino",
  },
  {
    name: "Isaac Souza",
    discipline: "Saltos Ornamentais",
    gender: "Masculino",
  },
  { name: "Dora Varella", discipline: "Skate", gender: "Feminino" },
  { name: "Isadora Pacheco", discipline: "Skate", gender: "Feminino" },
  { name: "Raicca Ventura", discipline: "Skate", gender: "Feminino" },
  { name: "Gabriela Mazetto", discipline: "Skate", gender: "Feminino" },
  { name: "Pâmela Rosa", discipline: "Skate", gender: "Feminino" },
  { name: "Rayssa Leal", discipline: "Skate", gender: "Feminino" },
  { name: "Augusto Akio", discipline: "Skate", gender: "Masculino" },
  { name: "Luigi Cini", discipline: "Skate", gender: "Masculino" },
  { name: "Pedro Barros", discipline: "Skate", gender: "Masculino" },
  { name: "Felipe Gustavo", discipline: "Skate", gender: "Masculino" },
  { name: "Giovanni Vianna", discipline: "Skate", gender: "Masculino" },
  { name: "Kelvin Hoefler", discipline: "Skate", gender: "Masculino" },
  { name: "Luana Silva", discipline: "Surfe", gender: "Feminino" },
  { name: "Tainá Hinckel", discipline: "Surfe", gender: "Feminino" },
  { name: "Tatiana Weston-Webb", discipline: "Surfe", gender: "Feminino" },
  { name: "Filipe Toledo", discipline: "Surfe", gender: "Masculino" },
  { name: "Gabriel Medina", discipline: "Surfe", gender: "Masculino" },
  { name: "João Chianca", discipline: "Surfe", gender: "Masculino" },
  { name: "Maria Clara Pacheco", discipline: "Taekwondo", gender: "Feminino" },
  { name: "Caroline Santos", discipline: "Taekwondo", gender: "Feminino" },
  { name: "Edival Pontes", discipline: "Taekwondo", gender: "Masculino" },
  { name: "Henrique Marques", discipline: "Taekwondo", gender: "Masculino" },
  { name: "Beatriz Haddad Maia", discipline: "Tênis", gender: "Feminino" },
  { name: "Laura Pigossi", discipline: "Tênis", gender: "Feminino" },
  { name: "Luisa Stefani", discipline: "Tênis", gender: "Feminino" },
  { name: "Thiago Monteiro", discipline: "Tênis", gender: "Masculino" },
  { name: "Thiago Wild", discipline: "Tênis", gender: "Masculino" },
  { name: "Bruna Alexandre", discipline: "Tênis de Mesa", gender: "Feminino" },
  { name: "Bruna Takahashi", discipline: "Tênis de Mesa", gender: "Feminino" },
  { name: "Giulia Takahashi", discipline: "Tênis de Mesa", gender: "Feminino" },
  {
    name: "Guilherme Teodoro",
    discipline: "Tênis de Mesa",
    gender: "Masculino",
  },
];
