export const disciplinesList = [
  "Águas Abertas",
  "Atletismo",
  "Badminton",
  "Basquete",
  "Boxe",
  "Canoagem Slalom",
  "Canoagem Velocidade",
  "Ciclismo BMX Racing",
  "Ciclismo BMX Freestyle",
  "Ciclismo Estrada",
  "Ciclismo Mountain Bike",
  "Esgrima",
  "Futebol",
  "Ginástica Artística",
  "Ginástica Rítmica",
  "Ginástica Trampolim",
  "Handebol",
  "Hipismo Adestramento",
  "Hipismo Completo",
  "Hipismo Saltos",
  "Judô",
  "Levantamento de Peso",
  "Natação",
  "Pentatlo Moderno",
  "Remo",
  "Rúgbi",
  "Saltos Ornamentais",
  "Skate",
  "Surfe",
  "Taekwondo",
  "Tênis",
  "Tênis de Mesa",
  "Tiro com Arco",
  "Tiro Esportivo",
  "Triatlo",
  "Vela",
  "Vôlei",
  "Vôlei de Praia",
  "Wrestling",
];
